project:
  type: website

website:
  title: "Alex Labuda" ## Add site URL below when you have one
  description: "Alex Labuda's personal blog and website"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/alexlabuda
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-labuda/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

