project:
  type: website
  output-dir: docs

website:
  title: "Alex Labuda" ## Add site URL below when you have one
  description: "Alex Labuda's personal blog and website"
  page-navigation: true
  back-to-top-navigation: false
  
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/alexlabuda
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-labuda/
        
  page-footer:
    left: >-
     &#169; 2023 Alex Labuda &#8729; Made with [Quarto](https://quarto.org)
    right: >-
      [Home](index.html) | [Blog](blog.html)
        
format:
  html: 
    theme: [flatly, theme.scss]

editor: source

